before:
  hooks:
    - task install-deps docs mocks
    - go mod tidy

builds:
  - id: argo-watcher
    main: ./cmd/argo-watcher
    binary: argo-watcher
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/shini4i/argo-watcher/cmd/argo-watcher/server.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: client
    main: ./cmd/client
    binary: client
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  # Server image
  - image_templates:
      - 'ghcr.io/shini4i/argo-watcher:{{ .Tag }}-amd64'
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=argo-watcher"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=MIT"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.server
    extra_files:
      - web/build
      - db
    ids:
      - argo-watcher

  - image_templates:
      - 'ghcr.io/shini4i/argo-watcher:{{ .Tag }}-arm64'
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=argo-watcher"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=MIT"
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.server
    extra_files:
      - web/build
      - db
    ids:
      - argo-watcher

  # Client image
  - image_templates:
      - 'ghcr.io/shini4i/argo-watcher-client:{{ .Tag }}-amd64'
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=argo-watcher-client"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=MIT"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.client
    ids:
      - client

  - image_templates:
      - 'ghcr.io/shini4i/argo-watcher-client:{{ .Tag }}-arm64'
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=argo-watcher-client"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=MIT"
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.client
    ids:
      - client

docker_manifests:
  - name_template: 'ghcr.io/shini4i/argo-watcher:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/shini4i/argo-watcher:{{ .Tag }}-amd64'
      - 'ghcr.io/shini4i/argo-watcher:{{ .Tag }}-arm64'

  - name_template: 'ghcr.io/shini4i/argo-watcher-client:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/shini4i/argo-watcher-client:{{ .Tag }}-amd64'
      - 'ghcr.io/shini4i/argo-watcher-client:{{ .Tag }}-arm64'

archives:
  - formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    args:
      - "sign-blob"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"

docker_signs:
  - cmd: cosign
    artifacts: manifests
    args:
      - "sign"
      - "${artifact}@${digest}"
      - "--yes"

checksum:
  name_template: 'checksums.txt'

changelog:
  use:
    github-native

release:
  prerelease: auto
  draft: false

  footer: |
    ## Docker Images
    - `ghcr.io/shini4i/argo-watcher:{{ .Tag }}`
    - `ghcr.io/shini4i/argo-watcher-client:{{ .Tag }}`
