FROM scratch

COPY argo-watcher /argo-watcher

COPY web/build /static
COPY db /db
COPY --from=golang:1.24-alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

USER 65534:65534

CMD ["/argo-watcher"]
