#######################
# Backend build
#######################
FROM golang:1.18-alpine3.16 as builder

WORKDIR /src

RUN apk add --no-cache ca-certificates

COPY . .

RUN GO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o client ./cmd/client

#######################
# Final image
#######################
FROM alpine:3.16

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /src/client /bin/client

ENTRYPOINT ["/bin/client"]
