#######################
# Backend build
#######################
FROM golang:1.18-alpine3.16 as builder

WORKDIR /src

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o mock ./cmd/mock

#######################
# Final image
#######################
FROM scratch

COPY --from=builder /src/mock /mock

ENTRYPOINT ["/mock"]
