site_name: Argo-Watcher
site_url: https://github.com/shini4i/argo-watcher
site_description: Documentation for Argo-Watcher project
site_author: Vadim Gedz

theme:
  name: 'material'

nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Git Integration: 'git-integration.md'
  - Development: "development.md"
  - Keycloak: "keycloak.md"

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
