site_name: Argo-Watcher
site_url: https://github.com/shini4i/argo-watcher
site_description: Documentation for Argo-Watcher project
site_author: Vadim Gedz

theme:
  name: 'material'
  logo: 'assets/logo.png'
  favicon: 'assets/favicon.ico'
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs

nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Git Integration: 'git-integration.md'
  - Development: "development.md"
  - Keycloak: "keycloak.md"

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
