site_name: Argo Watcher
site_url: https://argo-watcher.readthedocs.io
site_description: Documentation for Argo Watcher - a feedback loop for your GitOps workflow
site_author: Vadim Gedz
copyright: Copyright &copy; 2023 - 2026 Vadim Gedz

repo_url: https://github.com/shini4i/argo-watcher
repo_name: shini4i/argo-watcher
edit_uri: edit/main/docs/

extra_css:
  - stylesheets/brand.css

theme:
  name: 'material'
  logo: 'assets/logo.png'
  favicon: 'assets/favicon.ico'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: 'index.md'
  - Concepts: 'concepts.md'
  - Installation: 'installation.md'
  - Git Integration: 'git-integration.md'
  - API Reference: 'api.md'
  - Notifications: 'notifications.md'
  - Keycloak: 'keycloak.md'
  - Development: 'development.md'
  - Style Guide: 'style.md'

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - git-committers:
      repository: shini4i/argo-watcher
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
  - social
  - glightbox
