name: Build and Publish docker images

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and publish argo-watcher image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            APP_VERSION: ${{ github.ref_name }}
          tags: |
            ghcr.io/shini4i/argo-watcher:${{ github.ref_name }}
          push: true

      - name: Build and publish argo-watcher-client image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.client
          tags: |
            ghcr.io/shini4i/argo-watcher-client:${{ github.ref_name }}
          push: true
