name: Build and Publish docker images

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate swagger docs
        run: make docs

      - name: Build argo-watcher binary
        run: make build VERSION=${{ github.ref_name }}

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Build argo-watcher UI
        run: make build-ui

      - name: Build and publish argo-watcher image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/shini4i/argo-watcher:${{ github.ref_name }}
          push: true

      - name: Update helm chart
        uses: shini4i/helm-charts-updater@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          gh_user: shini4i
          gh_repo: charts
          chart_name: argo-watcher
          app_version: ${{ github.ref_name }}
          update_chart_annotations: true
